const data = [
  {
    id: 1,
    title: 'React Awesome Shop',
    image: '/images/awesome-shop.png',
    description:
      'フロントエンドをReact、バックエンドをFirebaseで構築したサーバーレスなショッピングサイト',
    githubURL: 'https://github.com/KYOYA-OGA/react-awesome-store-JP',
    demoURL: 'https://awesome-shop-ja.web.app/',
    stacks: [
      'React',
      'TypeScript',
      'Firebase',
      'Stripe',
      'Algolia',
      'Firebase Functions',
    ],
  },
  {
    id: 2,
    image: '/images/comfy-store.png',
    title: 'React Comfy Store',
    description: 'SPAで構築された架空のネットショップ',
    githubURL: 'https://github.com/KYOYA-OGA/react-comfy-store-demo',
    demoURL: 'https://react-comfy-store-demo.netlify.app',
    stacks: ['React', 'styled-component', 'Auth0', 'Stripe'],
  },
  {
    id: 3,
    title: 'Github User Search',
    image: '/images/github-user.png',
    description:
      'Github APIを通じてユーザーを検索して各種情報を確認できるアプリ',
    githubURL: 'https://github.com/KYOYA-OGA/search-github-user',
    demoURL: 'https://react-github-user-searching.netlify.app',
    stacks: ['React', 'styled-component', 'Auth0'],
  },
  {
    id: 4,
    title: 'e-VENTs',
    image: '/images/next-event.png',
    description:
      'フロントエンドをNext.js、バックエンドをStrapiで構築したイベント作成アプリ',
    githubURL: 'https://github.com/KYOYA-OGA/next-events',
    demoURL: 'https://next-events-nine-xi.vercel.app',
    stacks: ['React', 'Next.js', 'Strapi', 'tailwindcss', 'Mapbox'],
  },
  {
    id: 5,
    title: 'Airbnb Clone',
    image: '/images/airbnb-clone.png',
    description: 'Next.js & tailwindCSS 製Airbnbクローン',
    githubURL: 'https://github.com/KYOYA-OGA/airbnb-clone',
    demoURL: 'https://airbnb-clone-opal-one.vercel.app',
    stacks: ['React', 'Next.js', 'tailwindcss', 'Mapbox'],
  },
  {
    id: 6,
    title: 'Dev.to Clone',
    image: '/images/dev-to-clone.png',
    description: 'Next.js & Firebase 製Dev.toクローン',
    githubURL: 'https://github.com/KYOYA-OGA/dev.to-clone',
    demoURL: 'https://dev-to-clone-flax.vercel.app/',
    stacks: ['React', 'Next.js', 'Firebase'],
  },
  {
    id: 7,
    title: 'Next Amazona',
    image: '/images/amazona.png',
    description: 'React(Next.js) & Material-UI & MongoDB 製ショッピングサイト',
    githubURL: 'https://github.com/KYOYA-OGA/next-amazona',
    demoURL: 'https://next-amazona-taupe.vercel.app',
    stacks: ['React', 'Next.js', 'Material-UI', 'MongoDB', 'Cloudinary'],
  },
  {
    id: 8,
    title: 'ファイル共有アプリ',
    image: '/images/fileshare-app.png',
    description:
      'ファイルをアップロードして共有できるサイト。メール送信機能付き。',
    githubURL: 'https://github.com/KYOYA-OGA/fileshare-app-frontend',
    demoURL: 'https://fileshare-app-frontend.vercel.app',
    stacks: [
      'React',
      'Next.js',
      'TypeScript',
      'tailwindcss',
      'Node.js',
      'MongoDB',
    ],
  },
  {
    id: 9,
    title: 'Venue LP',
    image: '/images/venue.png',
    description: 'Next.js製それっぽいランディングページ',
    githubURL: 'https://github.com/KYOYA-OGA/venue_lp',
    demoURL: 'https://venue-lp.vercel.app',
    stacks: ['React', 'Next.js'],
  },
  {
    id: 10,
    title: 'HOKUSAI',
    image: '/images/hokusai.png',
    description: 'Next.js製ギャラリーサイト',
    githubURL: 'https://github.com/KYOYA-OGA/hokusai',
    demoURL: 'https://hokusai.vercel.app',
    stacks: ['React', 'Next.js', 'Bootstrap'],
  },
  {
    id: 11,
    title: 'YouTube Clone',
    image: '/images/youtube-clone.jpg',
    description:
      'React + Redux + firebase + YouTube DATA API で作った YouTube クローン',
    githubURL: 'https://github.com/KYOYA-OGA/youtube-clone',
    demoURL: 'https://not-real-yt.firebaseapp.com/',
    stacks: ['React', 'firebase', 'Redux'],
  },
]
export default data
